#!/usr/bin/python2.4
# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='protorpc.Type',
  filename='Type',
  values=[
    descriptor.EnumValueDescriptor(
      name='REQUEST', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE_CANCEL', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE_FAILED', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE_NOT_IMPLEMENTED', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DISCONNECT', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DESCRIPTOR_REQUEST', index=6, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DESCRIPTOR_RESPONSE', index=7, number=8,
      options=None,
      type=None),
  ],
  options=None,
)


REQUEST = 1
RESPONSE = 2
RESPONSE_CANCEL = 3
RESPONSE_FAILED = 4
RESPONSE_NOT_IMPLEMENTED = 5
DISCONNECT = 6
DESCRIPTOR_REQUEST = 7
DESCRIPTOR_RESPONSE = 8



_MESSAGE = descriptor.Descriptor(
  name='Message',
  full_name='protorpc.Message',
  filename='Message.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='protorpc.Message.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='protorpc.Message.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='protorpc.Message.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='buffer', full_name='protorpc.Message.buffer', index=3,
      number=4, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_DESCRIPTORRESPONSE = descriptor.Descriptor(
  name='DescriptorResponse',
  full_name='protorpc.DescriptorResponse',
  filename='Message.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='desc', full_name='protorpc.DescriptorResponse.desc', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='deps', full_name='protorpc.DescriptorResponse.deps', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='serviceName', full_name='protorpc.DescriptorResponse.serviceName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MESSAGE.fields_by_name['type'].enum_type = _TYPE
_DESCRIPTORRESPONSE.fields_by_name['deps'].message_type = _DESCRIPTORRESPONSE

class Message(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MESSAGE

class DescriptorResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DESCRIPTORRESPONSE

